# Generated by Sharpmake -- Do not edit !
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := \
	SimpleTestProject \

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

SimpleTestProject: 
	@echo " ==== Building SimpleTestProject ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f simpletestproject_linux_clang.make

clean:
	@${MAKE} --no-print-directory -C . -f simpletestproject_linux_clang.make clean

help:
	@echo "Usage: make [config = name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   SimpleTestProject"

