language: cpp

compiler:
  - gcc
  - clang

matrix:
  include:
    - os: linux
      compiler: gcc
      env: COMPILER=gcc

    - os: linux
      compiler: clang
      env: COMPILER=clang

env:
  - CONFIGURATION=debug
  - CONFIGURATION=release

script:
  - cd projects && make -f simpletestsolution_linux_$COMPILER.make config=$CONFIGURATION
  - ./.temp/bin/simpletestsolution_linux_$COMPILER_$CONFIGURATION
