language: cpp
os: linux

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "SZhJILSCc8C5Bty/S8u34roV0FpdLSCnaD01UFJh3RFh+9RhtHdTqoaEuYlvmJlAadCdfrCUAh6nBddv7Xfgr4yO+Ee5mnc180fW3xUBBzC1p2umtU7P8BeKlbHhxmkjYQ3YKE1W8ifyyZsjZxWEa3i/qNlXJMgdB0QqpnCopkG7BK2Y8tM0TK6F0yv36yn/a+IC3H8Gm/ojapTpECNbv67lPDEpyC/TWoNSir0OTPfsoD6ndCsJWfIJvpEJj/vxHuCP1LmxoS4US1xiEeglka4C4/pf3MfoJy68BSiKKT07LL/sEU/6G1NdcupVrfCOu3ng9MQqvGBIGR8634iAzaxcl9EO5PuglOUP99BlCpAXPoBLOH0KxkX1y02phM0HXhwDQVPKID3CMBhSi3TwE2Pw8E0t3tn5lRzgQh289PTJbOaycWJ9zp72qIA87TdN3uWJfbbOzBYWzV7S451uBr/1FfK6FcbHneZdKB6khdfiSVLtEILfV92JGCLgP1o7Nxv5UvQObcgZ7CFktciPvRCcP1RHiOq+kXPgiUg9QPbybc1soGovZOWiSfJbrfVzyy3GUZyAVw2QUo1Les/0D84nEsOMsb2msGxotipf4J/EVr6Ir/rA/7rdRpQJv4Hv+rsYtZv+mZwT0iwUsMJL/yArtecaiq5MJlQUBj0fEJc="

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

script:
  - ./build_and_run.sh $CC $CONFIG

# jobs need to be explicit so we don't overload coverity
jobs:
  include:
    - compiler: gcc
      env: CONFIG=debug
    - compiler: gcc
      env: CONFIG=release
      if: branch != coverity_scan
    - compiler: clang
      env: CONFIG=debug
      if: branch != coverity_scan
    - compiler: clang
      env: CONFIG=release
      if: branch != coverity_scan
    - compiler: gcc
      env: CONFIG=debug GCOV=1
      if: branch != coverity_scan
    - compiler: gcc
      env: CONFIG=release GCOV=1
      if: branch != coverity_scan

addons:
  coverity_scan:
    project:
      name: "kudaba/simpletest_test"
      description: "Unit tests for simpletest, a simple unit testing framework"
    notification_email: chris@chrissavoie.com
    build_command: "./build_and_run.sh gcc debug"
    branch_pattern: coverity_scan
