language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      env:
        - COMPILER=gcc
        - CONFIGURATION=debug

    - os: linux
      compiler: gcc
      env:
        - COMPILER=gcc
        - CONFIGURATION=release

    - os: linux
      compiler: clang
      env:
        - COMPILER=clang
        - CONFIGURATION=debug
      
    - os: linux
      compiler: clang
      env:
        - COMPILER=clang
        - CONFIGURATION=release

script:
  - ./build_and_run.sh $COMPILER $CONFIGURATION